import 'package:flutter/material.dart';

class AssetsConstants{

  static const String _jpegPath = 'assets/jpegs';
  static const String _pngPath = 'assets/pngs';
  static const String shyamSteelLogo = '$_jpegPath/shyam_steel_logo.jpg';
  static const String attendance_img = '$_pngPath/login_button_attendance.png';
  static const String logout_background = '$_pngPath/logout_background.png';
  static const String shyam_steel_logo_round = '$_pngPath/shyam_steel_logo_round.png';
  static const String bar_chart_icon = '$_pngPath/bar_chart_icon.png';
  static const String clock_icon = '$_pngPath/clock_img.png';
  static const String absent_image = '$_pngPath/absent_image.png';
  static const String bike_unselected = '$_pngPath/bike_unselected.png';
  static const String bike_selected = '$_pngPath/bike_selected.png';
  static const String car_unselected = '$_pngPath/car_unselected.png';
  static const String car_selected = '$_pngPath/car_selected.png';
  static const String others_unselected = '$_pngPath/others_unselected.png';
  static const String others_selected = '$_pngPath/others_selected.png';
  static const String odometer_no_image = '$_pngPath/odometer_no_image.png';
  static const String odometer_camera = '$_pngPath/odometer_camera.png';
  static const String dealer_menu_background = '$_pngPath/dealer_menu_background.png';
  static const String distributor_menu_background = '$_pngPath/distributor_menu_background.png';
  static const String subdealer_menu_background = '$_pngPath/subdealer_menu_background.png';
  static const String dealer_menu_icon = '$_pngPath/dealer_menu_icon.png';
  static const String subdealer_menu_icon = '$_pngPath/subdealer_menu_icon.png';
  static const String distributor_menu_icon = '$_pngPath/distributor_menu_icon.png';
  static const String engineer_menu_icon = '$_pngPath/engineer_menu_icon.png';
  static const String mason_menu_icon = '$_pngPath/mason_menu_icon.png';
  static const String petty_con_menu_icon = '$_pngPath/petty_con_menu_icon.png';
  static const String ihb_owner_menu_icon = '$_pngPath/ihb_owner_menu_icon.png';
  static const String branches_menu_icon = '$_pngPath/branches_menu_icon.png';
  static const String account_summary_purple_box = '$_pngPath/account_summary_purple_box.png';
  static const String calender_icon = '$_pngPath/calender_icon.png';
  static const String account_status_icon = '$_pngPath/account_status_icon.png';
  static const String call_icon = '$_pngPath/call_icon.png';
  static const String click_here = '$_pngPath/click_here.png';
  static const String location = '$_pngPath/location.png';
  static const String earth_pin = '$_pngPath/earth-pin.png';
  static const String location_pin = '$_pngPath/location_pin.png';
  static const String account_status_box = '$_pngPath/account_status_box.png';
  static const String dizzy = '$_pngPath/dizzy.png';
  static const String sad_face = '$_pngPath/sad-face.png';
  static const String moderate_face = '$_pngPath/moderate_face.png';
  static const String happy_face = '$_pngPath/happy_face.png';
  static const String very_happy_face = '$_pngPath/very_happy_face.png';
  static const String business_survey_icon = '$_pngPath/business_survey_icon.png';
  static const String discussion_icon = '$_pngPath/discussion_icon.png';
  static const String action_plan_icon = '$_pngPath/action_plan_icon.png';
  static const String select_follow_up_date_image = '$_pngPath/select_follow_up_date_image.png';
  static const String next_follow_up_human = '$_pngPath/next_follow_up_human.png';
  static const String side_bar_profile_box = '$_pngPath/side_bar_profile_box.png';
  static const String side_bar_back_button = '$_pngPath/side_bar_back_button.png';
  static const String no_profile_pic = '$_pngPath/no_profile_pic.png';
  static const String side_bar_cam = '$_pngPath/side_bar_cam.png';
  static const String tier_logo = '$_pngPath/tier_logo.png';
  static const String activity = '$_pngPath/activity.png';
  static const String sale_icon = '$_pngPath/sale_icon.png';
  static const String blue_background_img = '$_pngPath/blue_background_img.png';
  static const String bronze_badge = '$_pngPath/bronze_badge.png';
  static const String silver_badge = '$_pngPath/silver_badge.png';

}